Add replica creation
lean-delivery/terraform-module-aws-elasticache pull request #1
Opened 2019-04-04 10:17 UTC by SiarheiShuliakouski

2019-04-11 11:36 UTC, vold029 requested changes
main.tf line 19:
`count = "${var.module_enabled && var.replication_enabled ? 0 : 0}"` 
is it correct or should be 
`count = "${var.module_enabled && var.replication_enabled ? 1 : 0}"`

2019-04-25 07:52 UTC, SiarheiShuliakouski commented
Hi vold029,

main.tf line 19 should be:

count = "${var.module_enabled && var.replication_enabled ? 0 : 0}"

2019-04-25 12:15 UTC, ToROxI commented on main.tf
> +resource "aws_elasticache_replication_group" "example" {
why resource named "example"?

2019-04-25 12:15 UTC, ToROxI commented on main.tf
> +  count = "${var.module_enabled && var.replication_enabled ? 0 : 0}"
should be 
```suggestion
  count = "${var.module_enabled && var.replication_enabled ? 0 : 1}"
```

2019-04-26 14:16 UTC, vold029 approved these changes
Approve

2019-04-30 09:14 UTC, merged